In [ ]:
1. Create a null vector of size 10 but the fifth value which is 1.

In [2]:
import numpy as np
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
2.Create a vector with values ranging from 10 to 49.


In [3]:
print(np.arange(10,49))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
3.Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
print(np.arange(0,9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
4.Find indices of non-zero elements from [1,2,0,0,4,0]

In [5]:
A = [1,2,0,0,4,0]
B = []

for i in range(len(A)):
    if A[i] != 0:
        B.append(i)
print(B)

[0, 1, 4]


In [ ]:
5.Create a 10x10 array with random values and find the minimum and maximum values.

In [8]:
x = np.random.random((10,10))
xmin, xmax = x.min(), x.max()
# print(x)
print("min : ",x.min())
print("max : ",x.max())

min :  0.003316782259973894
max :  0.9873058118421874


In [ ]:
6.Create a random vector of size 30 and find the mean value.

In [7]:
x = np.random.random((30))
print("Mean is : ",x.mean())

Mean is :  0.507728910006804
